
DECLARE
NUM NUMBER(15);
SUM_SALARY NUMBER(15);
AVG_SALARY NUMBER(15,2);
BEGIN
SELECT COUNT(*), SUM(SALARY), ROUND(AVG(SALARY),2) INTO NUM, SUM_SALARY, AVG_SALARY FROM EMPLOYEES;
DBMS_OUTPUT.PUT_LINE('총 사원의 수 : '||NUM);
DBMS_OUTPUT.PUT_LINE('급여의 합 : '||SUM_SALARY);
DBMS_OUTPUT.PUT_LINE('급여의 평균 : '||AVG_SALARY);
END;
/

DECLARE
ROW_TABLE EMPLOYEES%ROWTYPE;
DNAME_TABLE DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
SELECT * INTO ROW_TABLE FROM EMPLOYEES WHERE FIRST_NAME ='Clara';
SELECT DEPARTMENT_NAME INTO DNAME_TABLE FROM DEPARTMENTS WHERE DEPARTMENT_ID=ROW_TABLE.DEPARTMENT_ID;
DBMS_OUTPUT.PUT_LINE('직무 : '|| ROW_TABLE.JOB_ID);
DBMS_OUTPUT.PUT_LINE('급여 : '|| ROW_TABLE.SALARY);
DBMS_OUTPUT.PUT_LINE('입사일자 : '|| ROW_TABLE.HIRE_DATE);
DBMS_OUTPUT.PUT_LINE('커미션 : '|| ROW_TABLE.COMMISSION_PCT);
DBMS_OUTPUT.PUT_LINE('부서명 : '|| DNAME_TABLE);
END;
/