--
create table emp03
as
select * from employees;
select * from emp03;  
select * from DEPARTMENTS;
update emp03 set DEPARTMENT_ID='30';
ROllBACK;
update emp03 set salary=salary*1.1;
update emp03 set HIRE_DATE=sysdate;

update emp03 set DEPARTMENT_ID=30 where DEPARTMENT_ID=10;
update emp03 set SALARY=SALARY*1.1 WHERE SALARY>=3000;'

select e.FIRST_NAME, dp.DEPARTMENT_NAME, dp.department_id, 
case
when dp.DEPARTMENT_NAME='Marketing' then salary*1.05
when dp.DEPARTMENT_NAME='Purchasing' then salary*1.1
when dp.DEPARTMENT_NAME='Human Resources' then salary*1.15
when dp.DEPARTMENT_NAME='IT' then salary*1.20
else salary
end newsalary
,salary "기존 급여"
FROM employees e join DEPARTMENTS dp 
on e.DEPARTMENT_ID=dp.DEPARTMENT_ID
order by newsalary
;

CREATE TABLE DEPT01(
ID NUMBER(3), --PK
NAME VARCHAR2(15) NOT NULL,
COUNTRY VARCHAR2(15) NOT NULL
);
ALTER TABLE DEPT01 ADD CONSTRAINT DEPT01_ID_PK PRIMARY KEY(ID);
ALTER TABLE DEPT01 DROP CONSTRAINT DEPT01_ID_PK;
INSERT INTO DEPT01 VALUES(10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT01 VALUES(20,'RESEARCH','DALLAS');
INSERT INTO DEPT01 VALUES(30,'SALES','CHICAGO');
INSERT INTO DEPT01 VALUES(40,'OPERATIONS','BOSTON');

INSERT INTO MEMBER VALUES(799,'ALLEN','SALESMAN',1000,30);
INSERT INTO MEMBER VALUES(800,'JONES','MANAGER',1000,50);

ALTER TABLE DEPT01 RENAME COLUMN COUNTRY TO REGION;
CREATE TABLE EMPL(
ID NUMBER(3),--PK
NAME VARCHAR(15) NOT NULL,
JOB VARCHAR(15) NOT NULL,
SALARY NUMBER(4) NOT NULL,
DEPT_ID NUMBER(3)--FK
);
ALTER TABLE EMPL ADD CONSTRAINT EMPL_ID_PK PRIMARY KEY(ID);
ALTER TABLE EMPL ADD CONSTRAINT EMPL_DEPT_ID_FK FOREIGN KEY(DEPT_ID) REFERENCES DEPT01(ID) ON DELETE CASCADE; 
INSERT INTO EMPL VALUES(799,'ALLEN','SALESMAN',1000,30);
INSERT INTO EMPL VALUES(800,'JONES','MANAGER',1000,40);
SELECT * FROM DEPT01;
SELECT * FROM EMPL;

UPDATE DEPT01 SET ID=40 WHERE ID=80;
SELECT * FROM DEPT01 D JOIN EMPL E ON D.ID=E.DEPT_ID; 

DROP TRIGGER DEPT_ID_TRG;

--트리거 생성

CREATE OR REPLACE TRIGGER DEPT_ID_TRG
AFTER UPDATE OF ID ON DEPT01
FOR EACH ROW
BEGIN
UPDATE EMPL 
SET DEPT_ID=:NEW.ID
WHERE DEPT_ID=:OLD.ID;
END;