CREATE TABLE CUSTOMER(
NO CHAR(5),                          --PK
NAME VARCHAR2(10) NOT NULL,          --이름
ID VARCHAR2(20)NOT NULL,             --UQ 아이디
PWD VARCHAR2(20)NOT NULL,            --비밀번호
BIRTH DATE,                          --생년월일
PHONE VARCHAR2(20),                  --UQ핸드폰번호
BOOKCOUNT NUMBER(3) DEFAULT 0,       --예매횟수
REGISTDATE DATE NOT NULL             --회원가입 일자
);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_NO_PK PRIMARY KEY(NO);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_ID_UQ UNIQUE(ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PHONE_UQ UNIQUE(PHONE);

CREATE TABLE HALL(            --상영관
NO CHAR(2),                   --PK
SEATS NUMBER(3) NOT NULL,     --좌석수
PRICE NUMBER(6) NOT NULL      --상영료
);

ALTER TABLE HALL ADD CONSTRAINT HALL_NO_PK PRIMARY KEY(NO);

CREATE TABLE CINEMA(
NO CHAR(2),                     --PK
NAME VARCHAR(30) NOT NULL,      --이름
RUNNINGTIME NUMBER(3) NOT NULL, --러닝타임
STATUS CHAR(1) DEFAULT 0        --현재상영여부
);
ALTER TABLE CINEMA ADD CONSTRAINT CINEMA_NO_PK PRIMARY KEY(NO);

DROP TABLE PLAYING;
CREATE TABLE PLAYING(
NO CHAR(3),                     --PK상영작NO
HALL_NO CHAR(2),                --FK상영관NO
CINEMA_NO CHAR(3),              --FK영화NO    
STARTTIME DATE NOT NULL,        --시작시간
REMAIN NUMBER(3) NOT NULL,      --잔여좌석
STATUS CHAR(1) DEFAULT 0        --상영상태
);
ALTER TABLE PLAYING ADD CONSTRAINT PLAING_NO_PK PRIMARY KEY(NO);
ALTER TABLE PLAYING ADD CONSTRAINT PLAING_CINEMA_NO_FK FOREIGN KEY(CINEMA_NO) REFERENCES CINEMA(NO) ON DELETE SET NULL;
ALTER TABLE PLAYING ADD CONSTRAINT PLAING_HALL_NO_FK FOREIGN KEY(HALL_NO) REFERENCES HALL(NO) ON DELETE SET NULL;

DROP TABLE BOOKING;

CREATE TABLE BOOKING(
NO CHAR(5),                          --PK 
PLAYING_NO CHAR(3),                  --FK상영작NO
CUSTOMER_NO CHAR(5),                 --FK고객NO 
CODE CHAR(15),                       --UQ예매 코드 생성 고객NO-상영작NO-예매NO로생성
AMOUNT NUMBER(2) NOT NULL,           --합계인원
PRICE NUMBER(7),                     --합계가격
BOOKING_DATE DATE NOT NULL           --예매날짜
);

ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_NO_PK PRIMARY KEY(NO);
ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_PLAYING_NO_FK FOREIGN KEY(PLAYING_NO) REFERENCES PLAYING(NO) ON DELETE SET NULL;
ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_CUSTOMER_NO_FK FOREIGN KEY(CUSTOMER_NO) REFERENCES CUSTOMER(NO) ON DELETE SET NULL;
ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_CODE_UQ UNIQUE(CODE);
